# Generated by Django 6.0.2 on 2026-02-19 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya Adı')),
            ],
            options={
                'verbose_name': 'Toxum Kateqoriyası',
                'verbose_name_plural': 'Toxum Kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='SeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Toxum Adı')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seeds.seedcategory')),
            ],
            options={
                'verbose_name': 'Toxum Növü',
                'verbose_name_plural': 'Toxum Növləri',
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdar')),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('ton', 'ton'), ('qram', 'qram'), ('ədəd', 'ədəd')], default='kg', max_length=20, verbose_name='Ölçü Vahidi')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Qiymət')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.seeditem', verbose_name='Toxum')),
            ],
            options={
                'verbose_name': 'Toxum Inventarı',
                'verbose_name_plural': 'Toxum Inventarları',
                'ordering': ['-created_at'],
            },
        ),
    ]
