# Generated by Django 6.0.2 on 2026-02-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0002_seed_manual_name_alter_seed_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='created_by',
        ),
        migrations.AddField(
            model_name='seed',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Əlavə məlumat'),
        ),
    ]
