# Generated by Django 6.0.2 on 2026-03-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0004_seed_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('ton', 'ton'), ('qram', 'qram')], default='kg', max_length=20, verbose_name='Ölçü Vahidi'),
        ),
    ]
