# Generated by Django 5.2.10 on 2026-03-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0006_seed_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seed',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Toxum Inventarı', 'verbose_name_plural': 'Toxum Inventarları'},
        ),
    ]
