# Generated by Django 6.0.2 on 2026-03-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0008_seed_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seed',
            new_name='seeds_seed_created_16d422_idx',
            old_name='seeds_seed_created_ca8e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='seed',
            new_name='seeds_seed_created_483c65_idx',
            old_name='seeds_seed_created_31c50b_idx',
        ),
        migrations.RenameIndex(
            model_name='seed',
            new_name='seeds_seed_created_10818e_idx',
            old_name='seeds_seed_created_f263c1_idx',
        ),
        migrations.RenameIndex(
            model_name='seed',
            new_name='seeds_seed_created_24f43f_idx',
            old_name='seeds_seed_created_95588b_idx',
        ),
    ]
