# Generated by Django 6.0.2 on 2026-04-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0009_rename_seeds_seed_created_ca8e2a_idx_seeds_seed_created_16d422_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Miqdar'),
        ),
    ]
