# Generated by Django 6.0.2 on 2026-04-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeds", "0010_alter_seed_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="seed",
            name="zero_price_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("internal", "Təsərrüfat daxilində yaranıb"),
                    ("existing", "Əvvəlcədən məndə var idi"),
                    ("free", "Pulsuz gəlib / hədiyyədir"),
                    ("other", "Digər"),
                ],
                max_length=20,
                null=True,
                verbose_name="0 məbləğ mənbəyi",
            ),
        ),
    ]
