# Generated by Django 6.0.2 on 2026-04-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0012_seed_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seed',
            options={'ordering': ['-date', '-time', '-created_at'], 'verbose_name': 'Toxum Inventarı', 'verbose_name_plural': 'Toxum Inventarları'},
        ),
    ]
