# Generated by Django 5.2.10 on 2026-02-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('quantity', models.IntegerField(verbose_name='Miqdar')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət')),
                ('type', models.CharField(choices=[('Traktor', 'Traktor'), ('Kənd təsərrüfatı aləti', 'Kənd təsərrüfatı aləti'), ('Digər', 'Digər')], default='Digər', max_length=50, verbose_name='Növ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alət',
                'verbose_name_plural': 'Alətlər',
                'ordering': ['-created_at'],
            },
        ),
    ]
