# Generated by Django 5.2.10 on 2026-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('toxumlar', 'Toxumlar'), ('aletler', 'Alətlər'), ('heyvanlar', 'Heyvanlar'), ('teserrufat', 'Təsərrüfat məhsulları'), ('xercler', 'Xərclər'), ('diger', 'Digər')], max_length=30)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
