# Generated by Django 6.0.2 on 2026-02-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='manual_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xüsusi Ad'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='tools.toolitem', verbose_name='Alət'),
        ),
    ]
