# Generated by Django 5.2.10 on 2026-03-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_tool_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Alət', 'verbose_name_plural': 'Alətlər'},
        ),
    ]
