# Generated by Django 6.0.2 on 2026-03-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_tool_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tool',
            new_name='tools_tool_created_f18f40_idx',
            old_name='tools_tool_created_8cfec7_idx',
        ),
        migrations.RenameIndex(
            model_name='tool',
            new_name='tools_tool_created_8401ad_idx',
            old_name='tools_tool_created_087153_idx',
        ),
        migrations.RenameIndex(
            model_name='tool',
            new_name='tools_tool_created_d6305c_idx',
            old_name='tools_tool_created_760bc8_idx',
        ),
        migrations.RenameIndex(
            model_name='tool',
            new_name='tools_tool_created_1ea0ad_idx',
            old_name='tools_tool_created_4f8fde_idx',
        ),
    ]
