# Generated by Django 6.0.2 on 2026-04-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_tool_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-date', '-time', '-created_at'], 'verbose_name': 'Alət', 'verbose_name_plural': 'Alətlər'},
        ),
    ]
