# Generated by Django 6.0.2 on 2026-02-19 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya Adı')),
            ],
            options={
                'verbose_name': 'Heyvan Kateqoriyası',
                'verbose_name_plural': 'Heyvan Kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='AnimalSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Alt Kateqoriya Adı')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='animals.animalcategory', verbose_name='Ana Kateqoriya')),
            ],
            options={
                'verbose_name': 'Heyvan Alt Kateqoriyası',
                'verbose_name_plural': 'Heyvan Alt Kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='İdentifikasiya No')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cins')),
                ('gender', models.CharField(choices=[('erkek', 'Erkək'), ('disi', 'Dişi')], default='erkek', max_length=10, verbose_name='Cinsiyyət')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Çəki')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qiymət')),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('satilib', 'Satılıb'), ('telef', 'Tələf olub')], default='aktiv', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals_created', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.animalsubcategory', verbose_name='Alt Kateqoriya')),
            ],
            options={
                'verbose_name': 'Heyvan',
                'verbose_name_plural': 'Heyvanlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
