# Generated by Django 6.0.2 on 2026-02-19 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_manual_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='breed',
        ),
        migrations.AddField(
            model_name='animal',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Əlavə məlumat'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
