# Generated by Django 6.0.2 on 2026-03-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_batch_id'),
        ('animals', '0003_remove_animal_breed_animal_additional_info_and_more'),
    ]

    operations = [
    ]
