# Generated by Django 6.0.2 on 2026-03-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_merge_20260312_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='batch_id',
        ),
        migrations.AddField(
            model_name='animal',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Miqdar'),
        ),
    ]
