# Generated by Django 6.0.2 on 2026-03-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_remove_animal_batch_id_animal_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='status',
        ),
    ]
