# Generated by Django 6.0.2 on 2026-03-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_remove_animal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Miqdar'),
        ),
    ]
