# Generated by Django 5.2.10 on 2026-03-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_animal_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Heyvan', 'verbose_name_plural': 'Heyvanlar'},
        ),
    ]
