# Generated by Django 6.0.2 on 2026-03-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_animal_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='animal',
            new_name='animals_ani_created_025539_idx',
            old_name='animals_an_created_55e49e_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animals_ani_created_727585_idx',
            old_name='animals_an_created_5cf02c_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animals_ani_created_236da0_idx',
            old_name='animals_an_created_f0e7bc_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animals_ani_created_13d7cd_idx',
            old_name='animals_an_created_8f5bf6_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animals_ani_created_cec84f_idx',
            old_name='animals_an_created_58d5f9_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animals_ani_identif_3b7097_idx',
            old_name='animals_an_identif_efe528_idx',
        ),
    ]
