# Generated by Django 6.0.2 on 2026-04-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0013_animal_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-date', '-time', '-created_at'], 'verbose_name': 'Heyvan', 'verbose_name_plural': 'Heyvanlar'},
        ),
    ]
