# Generated by Django 5.2.10 on 2026-02-19 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Kateqoriya')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Məbləğ')),
                ('description', models.TextField(blank=True, verbose_name='İzah')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Tarix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xərc',
                'verbose_name_plural': 'Xərclər',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
