# Generated by Django 5.2.10 on 2026-02-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xercler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('SƏ', 'Səpin'), ('YEM', 'Heyvan yemi'), ('YAN', 'Yanacaq'), ('GUB', 'Gübrə'), ('TEM', 'Təmir'), ('DIG', 'Digər')], max_length=50, verbose_name='Kateqoriya'),
        ),
    ]
