# Generated by Django 5.2.10 on 2026-03-14 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('category', models.CharField(choices=[('vaksinasiya', 'Vaksinasiya'), ('odenis', 'Ödəniş'), ('ekin', 'Əkin'), ('diger', 'Digər')], default='diger', max_length=20, verbose_name='Kateqoriya')),
                ('due_date', models.DateField(verbose_name='Tarix')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlanıb')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xatırlatma',
                'verbose_name_plural': 'Xatırlatmalar',
                'ordering': ['due_date'],
            },
        ),
    ]
