# Generated by Django 6.0.2 on 2026-04-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_system_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockalertrule',
            name='source_type',
            field=models.CharField(choices=[('seed', 'Toxum'), ('tool', 'Alət'), ('farm', 'Təsərrüfat məhsulu'), ('animal', 'Heyvan')], max_length=20),
        ),
    ]
