# Generated by Django 6.0.2 on 2026-04-02 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Doğum günü')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İstifadəçi profili',
                'verbose_name_plural': 'İstifadəçi profilləri',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-poçt')),
                ('purpose', models.CharField(choices=[('signup', 'Qeydiyyat'), ('profile_email', 'Profil e-poçtu')], max_length=32, verbose_name='Təyinat')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('expires_at', models.DateTimeField(verbose_name='Bitmə vaxtı')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Təsdiq vaxtı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-poçt təsdiqi',
                'verbose_name_plural': 'E-poçt təsdiqləri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose'], name='users_email_email_bd2a51_idx'), models.Index(fields=['user', 'purpose'], name='users_email_user_id_19a3e6_idx')],
            },
        ),
    ]
