# Generated by Django 6.0.2 on 2026-03-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmproduct',
            name='unit',
            field=models.CharField(choices=[('kq', 'kq'), ('ton', 'ton'), ('qram', 'qram'), ('litr', 'litr'), ('ml', 'millilitr'), ('ədəd', 'ədəd'), ('dəstə', 'dəstə'), ('bağlama', 'bağlama')], max_length=20, verbose_name='Ölçü Vahidi'),
        ),
        migrations.AlterField(
            model_name='farmproductitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('kq', 'kq'), ('ton', 'ton'), ('qram', 'qram'), ('litr', 'litr'), ('ml', 'millilitr'), ('ədəd', 'ədəd'), ('dəstə', 'dəstə'), ('bağlama', 'bağlama')], max_length=20, null=True, verbose_name='Ölçü Vahidi'),
        ),
    ]
