# Generated by Django 5.2.10 on 2026-03-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_products', '0003_farmproduct_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmproduct',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Təsərrüfat Məhsulu', 'verbose_name_plural': 'Təsərrüfat Məhsulları'},
        ),
    ]
