# Generated by Django 6.0.2 on 2026-03-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_products', '0005_farmproduct_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='farmproduct',
            new_name='farm_produc_created_13233b_idx',
            old_name='farm_produc_created_f970e5_idx',
        ),
        migrations.RenameIndex(
            model_name='farmproduct',
            new_name='farm_produc_created_bf1d20_idx',
            old_name='farm_produc_created_1bbc66_idx',
        ),
        migrations.RenameIndex(
            model_name='farmproduct',
            new_name='farm_produc_created_26c09f_idx',
            old_name='farm_produc_created_322675_idx',
        ),
        migrations.RenameIndex(
            model_name='farmproduct',
            new_name='farm_produc_created_f6fdb3_idx',
            old_name='farm_produc_created_cf6ab6_idx',
        ),
        migrations.RenameIndex(
            model_name='farmproduct',
            new_name='farm_produc_created_983cfc_idx',
            old_name='farm_produc_created_24d89e_idx',
        ),
    ]
