# Generated by Django 6.0.2 on 2026-04-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_products', '0006_rename_farm_produc_created_f970e5_idx_farm_produc_created_13233b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Miqdar'),
        ),
    ]
