# Generated by Django 6.0.2 on 2026-04-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_products', '0009_farmproduct_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmproduct',
            options={'ordering': ['-date', '-time', '-created_at'], 'verbose_name': 'Təsərrüfat Məhsulu', 'verbose_name_plural': 'Təsərrüfat Məhsulları'},
        ),
    ]
