# Generated by Django 5.2.10 on 2026-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdar')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət')),
                ('unit', models.CharField(default='kg', max_length=10, verbose_name='Ölçü vahidi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Toxum',
                'verbose_name_plural': 'Toxumlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
