# Generated by Django 5.2.10 on 2026-02-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('ton', 'ton'), ('qram', 'qram'), ('ədəd', 'ədəd')], default='kg', max_length=10, verbose_name='Ölçü vahidi'),
        ),
    ]
