# Generated by Django 5.2.10 on 2026-02-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxum', '0002_alter_seed_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='category',
            field=models.CharField(choices=[('dənli', 'Dənli Bitkilər'), ('tərəvəz', 'Tərəvəz'), ('meyvə', 'Meyvə'), ('digər', 'Digər')], default='digər', max_length=20, verbose_name='Kateqoriya'),
        ),
        migrations.AddField(
            model_name='seed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seeds/', verbose_name='Şəkil'),
        ),
    ]
