# Generated by Django 5.2.10 on 2026-02-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toxum', '0003_seed_category_seed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='category',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='image',
        ),
    ]
