# Generated by Django 6.0.2 on 2026-02-19 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Məbləğ')),
                ('category', models.CharField(choices=[('toxum', 'Toxum'), ('alet', 'Alət'), ('heyvanlar', 'Heyvanlar'), ('yem', 'Yem'), ('diger', 'Digər')], default='diger', max_length=20, verbose_name='Kateqoriya')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıqlama')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Tarix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xərc',
                'verbose_name_plural': 'Xərclər',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
