# Generated by Django 6.0.2 on 2026-02-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya Adı')),
            ],
            options={
                'verbose_name': 'Xərc Kateqoriyası',
                'verbose_name_plural': 'Xərc Kateqoriyaları',
            },
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.CreateModel(
            name='ExpenseSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Alt Kateqoriya Adı')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='expenses.expensecategory', verbose_name='Ana Kateqoriya')),
            ],
            options={
                'verbose_name': 'Xərc Alt Kateqoriyası',
                'verbose_name_plural': 'Xərc Alt Kateqoriyaları',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensesubcategory', verbose_name='Alt Kateqoriya'),
        ),
    ]
