# Generated by Django 6.0.2 on 2026-02-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensecategory_remove_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='manual_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xüsusi Ad'),
        ),
    ]
