# Generated by Django 6.0.2 on 2026-02-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_manual_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.AddField(
            model_name='expense',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Əlavə məlumat'),
        ),
    ]
