# Generated by Django 6.0.2 on 2026-02-19 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('expenses', '0004_remove_expense_description_expense_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='expense',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
