# Generated by Django 6.0.2 on 2026-03-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_created_419f8b_idx',
            old_name='expenses_ex_created_ead3ca_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_created_effecc_idx',
            old_name='expenses_ex_created_fc6c10_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_created_a40edc_idx',
            old_name='expenses_ex_created_e20584_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_created_0b8a71_idx',
            old_name='expenses_ex_created_6fd6f7_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_content_632935_idx',
            old_name='expenses_ex_content_835246_idx',
        ),
    ]
