# Generated by Django 6.0.2 on 2026-04-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_expense_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-time', '-created_at'], 'verbose_name': 'Xərc', 'verbose_name_plural': 'Xərclər'},
        ),
    ]
