# Generated by Django 6.0.2 on 2026-04-25 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('expenses', '0010_alter_expense_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_by', 'created_at'], name='expenses_ex_created_e6798f_idx'),
        ),
    ]
