# Generated by Django 6.0.2 on 2026-03-01 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_text', models.BooleanField(default=False)),
                ('auto_sync', models.BooleanField(default=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('litr', 'Litr'), ('bas', 'Baş')], default='kg', max_length=10)),
                ('currency', models.CharField(choices=[('AZN', 'Azerbaijan Manat'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='AZN', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
