# Generated by Django 5.2.10 on 2026-03-23 07:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Təchizatçı Adı')),
                ('category', models.CharField(choices=[('Toxum', 'Toxum'), ('Gübrə', 'Gübrə'), ('Alətlər', 'Alətlər'), ('Heyvan', 'Heyvan'), ('Digər', 'Digər')], default='Digər', max_length=50, verbose_name='Kateqoriya')),
                ('location', models.CharField(max_length=200, verbose_name='Ünvan')),
                ('rating', models.IntegerField(default=5, verbose_name='Reytinq')),
                ('last_order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Son Sifariş Tarixi')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Seçilmiş')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon Nömrəsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Təchizatçı',
                'verbose_name_plural': 'Təchizatçılar',
                'ordering': ['-is_favorite', '-created_at'],
            },
        ),
    ]
