# Generated by Django 6.0.2 on 2026-03-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_sync_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicesyncstate',
            new_name='sync_device_user_id_e61509_idx',
            old_name='sync_device_user_id_8fe63b_idx',
        ),
        migrations.RenameIndex(
            model_name='devicesyncstate',
            new_name='sync_device_user_id_96b752_idx',
            old_name='sync_device_user_id_1e0ca0_idx',
        ),
        migrations.RenameIndex(
            model_name='syncoperation',
            new_name='sync_syncop_user_id_6ddfa5_idx',
            old_name='sync_syncop_user_id_79f090_idx',
        ),
        migrations.RenameIndex(
            model_name='syncoperation',
            new_name='sync_syncop_user_id_5e1c06_idx',
            old_name='sync_syncop_user_id_0e2dda_idx',
        ),
        migrations.RenameIndex(
            model_name='syncoperation',
            new_name='sync_syncop_user_id_651d80_idx',
            old_name='sync_syncop_user_id_427c8b_idx',
        ),
    ]
