# Generated by Django 6.0.2 on 2026-04-25 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_rename_sync_device_user_id_8fe63b_idx_sync_device_user_id_e61509_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['user', 'status', '-processed_at'], name='sync_syncop_user_id_263e08_idx'),
        ),
    ]
