# Generated by Django 6.0.2 on 2026-03-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0004_income_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='income',
            new_name='incomes_inc_created_6a1f2d_idx',
            old_name='incomes_inc_created_31f95c_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='incomes_inc_created_6c262a_idx',
            old_name='incomes_inc_created_9dd1c1_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='incomes_inc_created_558f72_idx',
            old_name='incomes_inc_created_3d4123_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='incomes_inc_created_6d4b70_idx',
            old_name='incomes_inc_created_35f249_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='incomes_inc_content_519a69_idx',
            old_name='incomes_inc_content_c31f56_idx',
        ),
    ]
