# Generated by Django 6.0.2 on 2026-04-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0005_rename_incomes_inc_created_31f95c_idx_incomes_inc_created_6a1f2d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Miqdar'),
        ),
    ]
