# Generated by Django 6.0.2 on 2026-04-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0007_income_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date', '-time', '-created_at'], 'verbose_name': 'Gəlir', 'verbose_name_plural': 'Gəlirlər'},
        ),
    ]
