# Generated by Django 6.0.2 on 2026-02-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('quantity', models.IntegerField(default=1, verbose_name='Miqdar')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Heyvan',
                'verbose_name_plural': 'Heyvanlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
