# Generated by Django 6.0.2 on 2026-02-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyvanlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('İnək', 'İnək'), ('Qoyun', 'Qoyun'), ('Toyuq', 'Toyuq'), ('At', 'At'), ('Keçi', 'Keçi'), ('Digər', 'Digər')], default='Digər', max_length=50, verbose_name='Növ'),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Çəki (kq)'),
        ),
    ]
