# Generated by Django 6.0.2 on 2026-02-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyvanlar', '0002_animal_type_animal_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='type',
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Çəki'),
        ),
    ]
