# Generated by Django 6.0.2 on 2026-03-08 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('az', 'Azərbaycan dili'), ('en', 'English'), ('ru', 'Русский')], default='az', max_length=10)),
                ('timezone', models.CharField(choices=[('Asia/Baku', 'Bakı (UTC+4)'), ('Europe/London', 'London (UTC+0)'), ('Europe/Moscow', 'Moskva (UTC+3)')], default='Asia/Baku', max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'İşıqlı'), ('dark', 'Qaranlıq')], default='light', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İstifadəçi Parametrləri',
                'verbose_name_plural': 'İstifadəçi Parametrləri',
            },
        ),
    ]
