# Generated by Django 6.0.2 on 2026-03-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='theme',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='currency',
            field=models.CharField(choices=[('AZN', 'AZN ₼'), ('EUR', 'EUR €'), ('USD', 'USD $')], default='AZN', max_length=5),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('litr', 'litr'), ('bas', 'baş')], default='kg', max_length=10),
        ),
    ]
