# Generated by Django 6.0.2 on 2026-04-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar_menu', '0006_alter_usersettings_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(choices=[('Etc/GMT+12', 'Baker Island'), ('Pacific/Pago_Pago', 'Pago Pago'), ('Pacific/Honolulu', 'Honolulu'), ('America/Anchorage', 'Anchorage'), ('America/Los_Angeles', 'Los Angeles'), ('America/Denver', 'Denver'), ('America/Chicago', 'Chicago'), ('America/New_York', 'New York'), ('America/Halifax', 'Halifax'), ('America/Sao_Paulo', 'Sao Paulo'), ('Atlantic/Cape_Verde', 'Praia'), ('Europe/London', 'London'), ('Europe/Berlin', 'Berlin'), ('Europe/Helsinki', 'Helsinki'), ('Europe/Istanbul', 'İstanbul'), ('Asia/Baku', 'Bakı'), ('Asia/Karachi', 'Kəraçi'), ('Asia/Dhaka', 'Dəkkə'), ('Asia/Bangkok', 'Banqkok'), ('Asia/Shanghai', 'Şanxay'), ('Asia/Tokyo', 'Tokio'), ('Australia/Brisbane', 'Brisbane'), ('Pacific/Guadalcanal', 'Honiara'), ('Pacific/Auckland', 'Auckland'), ('Pacific/Fakaofo', 'Fakaofo'), ('Pacific/Kiritimati', 'Kiritimati')], default='Asia/Baku', max_length=50),
        ),
    ]
